-- Insertions pour 200 utilisateurs
INSERT INTO users(nom, prenom, email, password, created_at) VALUES
    ('Utilisateur1', 'Prenom1', 'user1@email.com', 'password1', CURRENT_DATE),
    ('Utilisateur2', 'Prenom2', 'user2@email.com', 'password2', CURRENT_DATE),
    ('Utilisateur3', 'Prenom3', 'user3@email.com', 'password3', CURRENT_DATE),
    ('Utilisateur4', 'Prenom4', 'user4@email.com', 'password4', CURRENT_DATE),
    ('Utilisateur5', 'Prenom5', 'user5@email.com', 'password5', CURRENT_DATE),
    ('Utilisateur6', 'Prenom6', 'user6@email.com', 'password6', CURRENT_DATE),
    ('Utilisateur7', 'Prenom7', 'user7@email.com', 'password7', CURRENT_DATE),
    ('Utilisateur8', 'Prenom8', 'user8@email.com', 'password8', CURRENT_DATE),
    ('Utilisateur9', 'Prenom9', 'user9@email.com', 'password9', CURRENT_DATE),
    ('Utilisateur10', 'Prenom10', 'user10@email.com', 'password10', CURRENT_DATE),
    ('Utilisateur11', 'Prenom11', 'user11@email.com', 'password11', CURRENT_DATE),
    ('Utilisateur12', 'Prenom12', 'user12@email.com', 'password12', CURRENT_DATE),
    ('Utilisateur13', 'Prenom13', 'user13@email.com', 'password13', CURRENT_DATE),
    ('Utilisateur14', 'Prenom14', 'user14@email.com', 'password14', CURRENT_DATE),
    ('Utilisateur15', 'Prenom15', 'user15@email.com', 'password15', CURRENT_DATE),
    ('Utilisateur16', 'Prenom16', 'user16@email.com', 'password16', CURRENT_DATE),
    ('Utilisateur17', 'Prenom17', 'user17@email.com', 'password17', CURRENT_DATE),
    ('Utilisateur18', 'Prenom18', 'user18@email.com', 'password18', CURRENT_DATE),
    ('Utilisateur19', 'Prenom19', 'user19@email.com', 'password19', CURRENT_DATE),
    ('Utilisateur20', 'Prenom20', 'user20@email.com', 'password20', CURRENT_DATE),
    ('Utilisateur21', 'Prenom21', 'user21@email.com', 'password21', CURRENT_DATE),
    ('Utilisateur22', 'Prenom22', 'user22@email.com', 'password22', CURRENT_DATE),
    ('Utilisateur23', 'Prenom23', 'user23@email.com', 'password23', CURRENT_DATE),
    ('Utilisateur24', 'Prenom24', 'user24@email.com', 'password24', CURRENT_DATE),
    ('Utilisateur25', 'Prenom25', 'user25@email.com', 'password25', CURRENT_DATE),
    ('Utilisateur26', 'Prenom26', 'user26@email.com', 'password26', CURRENT_DATE),
    ('Utilisateur27', 'Prenom27', 'user27@email.com', 'password27', CURRENT_DATE),
    ('Utilisateur28', 'Prenom28', 'user28@email.com', 'password28', CURRENT_DATE),
    ('Utilisateur29', 'Prenom29', 'user29@email.com', 'password29', CURRENT_DATE),
    ('Utilisateur30', 'Prenom30', 'user30@email.com', 'password30', CURRENT_DATE),
    ('Utilisateur31', 'Prenom31', 'user31@email.com', 'password31', CURRENT_DATE),
    ('Utilisateur32', 'Prenom32', 'user32@email.com', 'password32', CURRENT_DATE),
    ('Utilisateur33', 'Prenom33', 'user33@email.com', 'password33', CURRENT_DATE),
    ('Utilisateur34', 'Prenom34', 'user34@email.com', 'password34', CURRENT_DATE),
    ('Utilisateur35', 'Prenom35', 'user35@email.com', 'password35', CURRENT_DATE),
    ('Utilisateur36', 'Prenom36', 'user36@email.com', 'password36', CURRENT_DATE),
    ('Utilisateur37', 'Prenom37', 'user37@email.com', 'password37', CURRENT_DATE),
    ('Utilisateur38', 'Prenom38', 'user38@email.com', 'password38', CURRENT_DATE),
    ('Utilisateur39', 'Prenom39', 'user39@email.com', 'password39', CURRENT_DATE),
    ('Utilisateur40', 'Prenom40', 'user40@email.com', 'password40', CURRENT_DATE),
    ('Utilisateur41', 'Prenom41', 'user41@email.com', 'password41', CURRENT_DATE),
    ('Utilisateur42', 'Prenom42', 'user42@email.com', 'password42', CURRENT_DATE),
    ('Utilisateur43', 'Prenom43', 'user43@email.com', 'password43', CURRENT_DATE),
    ('Utilisateur44', 'Prenom44', 'user44@email.com', 'password44', CURRENT_DATE),
    ('Utilisateur45', 'Prenom45', 'user45@email.com', 'password45', CURRENT_DATE),
    ('Utilisateur46', 'Prenom46', 'user46@email.com', 'password46', CURRENT_DATE),
    ('Utilisateur47', 'Prenom47', 'user47@email.com', 'password47', CURRENT_DATE),
    ('Utilisateur48', 'Prenom48', 'user48@email.com', 'password48', CURRENT_DATE),
    ('Utilisateur49', 'Prenom49', 'user49@email.com', 'password49', CURRENT_DATE),
    ('Utilisateur50', 'Prenom50', 'user50@email.com', 'password50', CURRENT_DATE),
    ('Utilisateur51', 'Prenom51', 'user51@email.com', 'password51', CURRENT_DATE),
    ('Utilisateur52', 'Prenom52', 'user52@email.com', 'password52', CURRENT_DATE),
    ('Utilisateur53', 'Prenom53', 'user53@email.com', 'password53', CURRENT_DATE),
    ('Utilisateur54', 'Prenom54', 'user54@email.com', 'password54', CURRENT_DATE),
    ('Utilisateur55', 'Prenom55', 'user55@email.com', 'password55', CURRENT_DATE),
    ('Utilisateur56', 'Prenom56', 'user56@email.com', 'password56', CURRENT_DATE),
    ('Utilisateur57', 'Prenom57', 'user57@email.com', 'password57', CURRENT_DATE),
    ('Utilisateur58', 'Prenom58', 'user58@email.com', 'password58', CURRENT_DATE),
    ('Utilisateur59', 'Prenom59', 'user59@email.com', 'password59', CURRENT_DATE),
    ('Utilisateur60', 'Prenom60', 'user60@email.com', 'password60', CURRENT_DATE),
    ('Utilisateur61', 'Prenom61', 'user61@email.com', 'password61', CURRENT_DATE),
    ('Utilisateur62', 'Prenom62', 'user62@email.com', 'password62', CURRENT_DATE),
    ('Utilisateur63', 'Prenom63', 'user63@email.com', 'password63', CURRENT_DATE),
    ('Utilisateur64', 'Prenom64', 'user64@email.com', 'password64', CURRENT_DATE),
    ('Utilisateur65', 'Prenom65', 'user65@email.com', 'password65', CURRENT_DATE),
    ('Utilisateur66', 'Prenom66', 'user66@email.com', 'password66', CURRENT_DATE),
    ('Utilisateur67', 'Prenom67', 'user67@email.com', 'password67', CURRENT_DATE),
    ('Utilisateur68', 'Prenom68', 'user68@email.com', 'password68', CURRENT_DATE),
    ('Utilisateur69', 'Prenom69', 'user69@email.com', 'password69', CURRENT_DATE),
    ('Utilisateur70', 'Prenom70', 'user70@email.com', 'password70', CURRENT_DATE),
    ('Utilisateur71', 'Prenom71', 'user71@email.com', 'password71', CURRENT_DATE),
    ('Utilisateur72', 'Prenom72', 'user72@email.com', 'password72', CURRENT_DATE),
    ('Utilisateur73', 'Prenom73', 'user73@email.com', 'password73', CURRENT_DATE),
    ('Utilisateur74', 'Prenom74', 'user74@email.com', 'password74', CURRENT_DATE),
    ('Utilisateur75', 'Prenom75', 'user75@email.com', 'password75', CURRENT_DATE),
    ('Utilisateur76', 'Prenom76', 'user76@email.com', 'password76', CURRENT_DATE),
    ('Utilisateur77', 'Prenom77', 'user77@email.com', 'password77', CURRENT_DATE),
    ('Utilisateur78', 'Prenom78', 'user78@email.com', 'password78', CURRENT_DATE),
    ('Utilisateur79', 'Prenom79', 'user79@email.com', 'password79', CURRENT_DATE),
    ('Utilisateur80', 'Prenom80', 'user80@email.com', 'password80', CURRENT_DATE),
    ('Utilisateur81', 'Prenom81', 'user81@email.com', 'password81', CURRENT_DATE),
    ('Utilisateur82', 'Prenom82', 'user82@email.com', 'password82', CURRENT_DATE),
    ('Utilisateur83', 'Prenom83', 'user83@email.com', 'password83', CURRENT_DATE),
    ('Utilisateur84', 'Prenom84', 'user84@email.com', 'password84', CURRENT_DATE),
    ('Utilisateur85', 'Prenom85', 'user85@email.com', 'password85', CURRENT_DATE),
    ('Utilisateur86', 'Prenom86', 'user86@email.com', 'password86', CURRENT_DATE),
    ('Utilisateur87', 'Prenom87', 'user87@email.com', 'password87', CURRENT_DATE),
    ('Utilisateur88', 'Prenom88', 'user88@email.com', 'password88', CURRENT_DATE),
    ('Utilisateur89', 'Prenom89', 'user89@email.com', 'password89', CURRENT_DATE),
    ('Utilisateur90', 'Prenom90', 'user90@email.com', 'password90', CURRENT_DATE),
    ('Utilisateur91', 'Prenom91', 'user91@email.com', 'password91', CURRENT_DATE),
    ('Utilisateur92', 'Prenom92', 'user92@email.com', 'password92', CURRENT_DATE),
    ('Utilisateur93', 'Prenom93', 'user93@email.com', 'password93', CURRENT_DATE),
    ('Utilisateur94', 'Prenom94', 'user94@email.com', 'password94', CURRENT_DATE),
    ('Utilisateur95', 'Prenom95', 'user95@email.com', 'password95', CURRENT_DATE),
    ('Utilisateur96', 'Prenom96', 'user96@email.com', 'password96', CURRENT_DATE),
    ('Utilisateur97', 'Prenom97', 'user97@email.com', 'password97', CURRENT_DATE),
    ('Utilisateur98', 'Prenom98', 'user98@email.com', 'password98', CURRENT_DATE),
    ('Utilisateur99', 'Prenom99', 'user99@email.com', 'password99', CURRENT_DATE),
    ('Utilisateur100', 'Prenom100', 'user100@email.com', 'password100', CURRENT_DATE),
    ('Utilisateur101', 'Prenom101', 'user101@email.com', 'password101', CURRENT_DATE),
    ('Utilisateur102', 'Prenom102', 'user102@email.com', 'password102', CURRENT_DATE),
    ('Utilisateur103', 'Prenom103', 'user103@email.com', 'password103', CURRENT_DATE),
    ('Utilisateur104', 'Prenom104', 'user104@email.com', 'password104', CURRENT_DATE),
    ('Utilisateur105', 'Prenom105', 'user105@email.com', 'password105', CURRENT_DATE),
    ('Utilisateur106', 'Prenom106', 'user106@email.com', 'password106', CURRENT_DATE),
    ('Utilisateur107', 'Prenom107', 'user107@email.com', 'password107', CURRENT_DATE),
    ('Utilisateur108', 'Prenom108', 'user108@email.com', 'password108', CURRENT_DATE),
    ('Utilisateur109', 'Prenom109', 'user109@email.com', 'password109', CURRENT_DATE),
    ('Utilisateur110', 'Prenom110', 'user110@email.com', 'password110', CURRENT_DATE),
    ('Utilisateur111', 'Prenom111', 'user111@email.com', 'password111', CURRENT_DATE),
    ('Utilisateur112', 'Prenom112', 'user112@email.com', 'password112', CURRENT_DATE),
    ('Utilisateur113', 'Prenom113', 'user113@email.com', 'password113', CURRENT_DATE),
    ('Utilisateur114', 'Prenom114', 'user114@email.com', 'password114', CURRENT_DATE),
    ('Utilisateur115', 'Prenom115', 'user115@email.com', 'password115', CURRENT_DATE),
    ('Utilisateur116', 'Prenom116', 'user116@email.com', 'password116', CURRENT_DATE),
    ('Utilisateur117', 'Prenom117', 'user117@email.com', 'password117', CURRENT_DATE),
    ('Utilisateur118', 'Prenom118', 'user118@email.com', 'password118', CURRENT_DATE),
    ('Utilisateur119', 'Prenom119', 'user119@email.com', 'password119', CURRENT_DATE),
    ('Utilisateur120', 'Prenom120', 'user120@email.com', 'password120', CURRENT_DATE),
    ('Utilisateur121', 'Prenom121', 'user121@email.com', 'password121', CURRENT_DATE),
    ('Utilisateur122', 'Prenom122', 'user122@email.com', 'password122', CURRENT_DATE),
    ('Utilisateur123', 'Prenom123', 'user123@email.com', 'password123', CURRENT_DATE),
    ('Utilisateur124', 'Prenom124', 'user124@email.com', 'password124', CURRENT_DATE),
    ('Utilisateur125', 'Prenom125', 'user125@email.com', 'password125', CURRENT_DATE),
    ('Utilisateur126', 'Prenom126', 'user126@email.com', 'password126', CURRENT_DATE),
    ('Utilisateur127', 'Prenom127', 'user127@email.com', 'password127', CURRENT_DATE),
    ('Utilisateur128', 'Prenom128', 'user128@email.com', 'password128', CURRENT_DATE),
    ('Utilisateur129', 'Prenom129', 'user129@email.com', 'password129', CURRENT_DATE),
    ('Utilisateur130', 'Prenom130', 'user130@email.com', 'password130', CURRENT_DATE),
    ('Utilisateur131', 'Prenom131', 'user131@email.com', 'password131', CURRENT_DATE),
    ('Utilisateur132', 'Prenom132', 'user132@email.com', 'password132', CURRENT_DATE),
    ('Utilisateur133', 'Prenom133', 'user133@email.com', 'password133', CURRENT_DATE),
    ('Utilisateur134', 'Prenom134', 'user134@email.com', 'password134', CURRENT_DATE),
    ('Utilisateur135', 'Prenom135', 'user135@email.com', 'password135', CURRENT_DATE),
    ('Utilisateur136', 'Prenom136', 'user136@email.com', 'password136', CURRENT_DATE),
    ('Utilisateur137', 'Prenom137', 'user137@email.com', 'password137', CURRENT_DATE),
    ('Utilisateur138', 'Prenom138', 'user138@email.com', 'password138', CURRENT_DATE),
    ('Utilisateur139', 'Prenom139', 'user139@email.com', 'password139', CURRENT_DATE),
    ('Utilisateur140', 'Prenom140', 'user140@email.com', 'password140', CURRENT_DATE),
    ('Utilisateur141', 'Prenom141', 'user141@email.com', 'password141', CURRENT_DATE),
    ('Utilisateur142', 'Prenom142', 'user142@email.com', 'password142', CURRENT_DATE),
    ('Utilisateur143', 'Prenom143', 'user143@email.com', 'password143', CURRENT_DATE),
    ('Utilisateur144', 'Prenom144', 'user144@email.com', 'password144', CURRENT_DATE),
    ('Utilisateur145', 'Prenom145', 'user145@email.com', 'password145', CURRENT_DATE),
    ('Utilisateur146', 'Prenom146', 'user146@email.com', 'password146', CURRENT_DATE),
    ('Utilisateur147', 'Prenom147', 'user147@email.com', 'password147', CURRENT_DATE),
    ('Utilisateur148', 'Prenom148', 'user148@email.com', 'password148', CURRENT_DATE),
    ('Utilisateur149', 'Prenom149', 'user149@email.com', 'password149', CURRENT_DATE),
    ('Utilisateur150', 'Prenom150', 'user150@email.com', 'password150', CURRENT_DATE),
    ('Utilisateur151', 'Prenom151', 'user151@email.com', 'password151', CURRENT_DATE),
    ('Utilisateur152', 'Prenom152', 'user152@email.com', 'password152', CURRENT_DATE),
    ('Utilisateur153', 'Prenom153', 'user153@email.com', 'password153', CURRENT_DATE),
    ('Utilisateur154', 'Prenom154', 'user154@email.com', 'password154', CURRENT_DATE),
    ('Utilisateur155', 'Prenom155', 'user155@email.com', 'password155', CURRENT_DATE),
    ('Utilisateur156', 'Prenom156', 'user156@email.com', 'password156', CURRENT_DATE),
    ('Utilisateur157', 'Prenom157', 'user157@email.com', 'password157', CURRENT_DATE),
    ('Utilisateur158', 'Prenom158', 'user158@email.com', 'password158', CURRENT_DATE),
    ('Utilisateur159', 'Prenom159', 'user159@email.com', 'password159', CURRENT_DATE),
    ('Utilisateur160', 'Prenom160', 'user160@email.com', 'password160', CURRENT_DATE),
    ('Utilisateur161', 'Prenom161', 'user161@email.com', 'password161', CURRENT_DATE),
    ('Utilisateur162', 'Prenom162', 'user162@email.com', 'password162', CURRENT_DATE),
    ('Utilisateur163', 'Prenom163', 'user163@email.com', 'password163', CURRENT_DATE),
    ('Utilisateur164', 'Prenom164', 'user164@email.com', 'password164', CURRENT_DATE),
    ('Utilisateur165', 'Prenom165', 'user165@email.com', 'password165', CURRENT_DATE),
    ('Utilisateur166', 'Prenom166', 'user166@email.com', 'password166', CURRENT_DATE),
    ('Utilisateur167', 'Prenom167', 'user167@email.com', 'password167', CURRENT_DATE),
    ('Utilisateur168', 'Prenom168', 'user168@email.com', 'password168', CURRENT_DATE),
    ('Utilisateur169', 'Prenom169', 'user169@email.com', 'password169', CURRENT_DATE),
    ('Utilisateur170', 'Prenom170', 'user170@email.com', 'password170', CURRENT_DATE),
    ('Utilisateur171', 'Prenom171', 'user171@email.com', 'password171', CURRENT_DATE),
    ('Utilisateur172', 'Prenom172', 'user172@email.com', 'password172', CURRENT_DATE),
    ('Utilisateur173', 'Prenom173', 'user173@email.com', 'password173', CURRENT_DATE),
    ('Utilisateur174', 'Prenom174', 'user174@email.com', 'password174', CURRENT_DATE),
    ('Utilisateur175', 'Prenom175', 'user175@email.com', 'password175', CURRENT_DATE),
    ('Utilisateur176', 'Prenom176', 'user176@email.com', 'password176', CURRENT_DATE),
    ('Utilisateur177', 'Prenom177', 'user177@email.com', 'password177', CURRENT_DATE),
    ('Utilisateur178', 'Prenom178', 'user178@email.com', 'password178', CURRENT_DATE),
    ('Utilisateur179', 'Prenom179', 'user179@email.com', 'password179', CURRENT_DATE),
    ('Utilisateur180', 'Prenom180', 'user180@email.com', 'password180', CURRENT_DATE),
    ('Utilisateur181', 'Prenom181', 'user181@email.com', 'password181', CURRENT_DATE),
    ('Utilisateur182', 'Prenom182', 'user182@email.com', 'password182', CURRENT_DATE),
    ('Utilisateur183', 'Prenom183', 'user183@email.com', 'password183', CURRENT_DATE),
    ('Utilisateur184', 'Prenom184', 'user184@email.com', 'password184', CURRENT_DATE),
    ('Utilisateur185', 'Prenom185', 'user185@email.com', 'password185', CURRENT_DATE),
    ('Utilisateur186', 'Prenom186', 'user186@email.com', 'password186', CURRENT_DATE),
    ('Utilisateur187', 'Prenom187', 'user187@email.com', 'password187', CURRENT_DATE),
    ('Utilisateur188', 'Prenom188', 'user188@email.com', 'password188', CURRENT_DATE),
    ('Utilisateur189', 'Prenom189', 'user189@email.com', 'password189', CURRENT_DATE),
    ('Utilisateur190', 'Prenom190', 'user190@email.com', 'password190', CURRENT_DATE),
    ('Utilisateur191', 'Prenom191', 'user191@email.com', 'password191', CURRENT_DATE),
    ('Utilisateur192', 'Prenom192', 'user192@email.com', 'password192', CURRENT_DATE),
    ('Utilisateur193', 'Prenom193', 'user193@email.com', 'password193', CURRENT_DATE),
    ('Utilisateur194', 'Prenom194', 'user194@email.com', 'password194', CURRENT_DATE),
    ('Utilisateur195', 'Prenom195', 'user195@email.com', 'password195', CURRENT_DATE),
    ('Utilisateur196', 'Prenom196', 'user196@email.com', 'password196', CURRENT_DATE),
    ('Utilisateur197', 'Prenom197', 'user197@email.com', 'password197', CURRENT_DATE),
    ('Utilisateur198', 'Prenom198', 'user198@email.com', 'password198', CURRENT_DATE),
    ('Utilisateur199', 'Prenom199', 'user199@email.com', 'password199', CURRENT_DATE),
    ('Utilisateur200', 'Prenom200', 'user200@email.com', 'password200', CURRENT_DATE);


-- Insertions pour 200 enquêtes
INSERT INTO enquete (id_users, age, region, emploi, lieu_de_vie, lieu_de_vie_CDAPH, lieu_de_vie_choix, besoin,
                     besoinDetail, submit_at)
VALUES
    (1, 19, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (2, 20, 'Bretagne', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (3, 21, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (4, 22, 'Grand-Est', 'Autre', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (5, 23, 'Pays de la Loire', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (6, 24, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (7, 25, 'Île-de-France', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (8, 26, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (9, 27, 'Bretagne', 'Autre', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (10, 28, 'Corse', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (11, 29, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (12, 30, 'Pays de la Loire', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (13, 31, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (14, 32, 'Île-de-France', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (15, 33, 'Normandie', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (16, 34, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (17, 35, 'Corse', 'Études supérieures', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (18, 36, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (19, 37, 'Pays de la Loire', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (20, 38, 'Guyane', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (21, 39, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (22, 40, 'Normandie', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (23, 41, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (24, 42, 'Corse', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (25, 43, 'Grand-Est', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (26, 44, 'Pays de la Loire', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (27, 45, 'Guyane', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (28, 46, 'Île-de-France', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (29, 47, 'Normandie', 'Autre', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (30, 48, 'Bretagne', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (31, 49, 'Corse', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (32, 50, 'Grand-Est', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (33, 51, 'Pays de la Loire', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (34, 52, 'Guyane', 'Autre', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (35, 53, 'Île-de-France', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (36, 54, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (37, 55, 'Bretagne', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (38, 56, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (39, 57, 'Grand-Est', 'Autre', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (40, 18, 'Pays de la Loire', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (41, 19, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (42, 20, 'Île-de-France', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (43, 21, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (44, 22, 'Bretagne', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (45, 23, 'Corse', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (46, 24, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (47, 25, 'Pays de la Loire', 'Études supérieures', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (48, 26, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (49, 27, 'Île-de-France', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (50, 28, 'Normandie', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (51, 29, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (52, 30, 'Corse', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (53, 31, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (54, 32, 'Pays de la Loire', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (55, 33, 'Guyane', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (56, 34, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (57, 35, 'Normandie', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (58, 36, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (59, 37, 'Corse', 'Autre', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (60, 38, 'Grand-Est', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (61, 39, 'Pays de la Loire', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (62, 40, 'Guyane', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (63, 41, 'Île-de-France', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (64, 42, 'Normandie', 'Autre', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (65, 43, 'Bretagne', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (66, 44, 'Corse', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (67, 45, 'Grand-Est', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (68, 46, 'Pays de la Loire', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (69, 47, 'Guyane', 'Autre', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (70, 48, 'Île-de-France', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (71, 49, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (72, 50, 'Bretagne', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (73, 51, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (74, 52, 'Grand-Est', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (75, 53, 'Pays de la Loire', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (76, 54, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (77, 55, 'Île-de-France', 'Études supérieures', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (78, 56, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (79, 57, 'Bretagne', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (80, 18, 'Corse', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (81, 19, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (82, 20, 'Pays de la Loire', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (83, 21, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (84, 22, 'Île-de-France', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (85, 23, 'Normandie', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (86, 24, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (87, 25, 'Corse', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (88, 26, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (89, 27, 'Pays de la Loire', 'Autre', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (90, 28, 'Guyane', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (91, 29, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (92, 30, 'Normandie', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (93, 31, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (94, 32, 'Corse', 'Autre', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (95, 33, 'Grand-Est', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (96, 34, 'Pays de la Loire', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (97, 35, 'Guyane', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (98, 36, 'Île-de-France', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (99, 37, 'Normandie', 'Autre', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (100, 38, 'Bretagne', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (101, 39, 'Corse', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (102, 40, 'Grand-Est', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (103, 41, 'Pays de la Loire', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (104, 42, 'Guyane', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (105, 43, 'Île-de-France', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (106, 44, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (107, 45, 'Bretagne', 'Études supérieures', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (108, 46, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (109, 47, 'Grand-Est', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (110, 48, 'Pays de la Loire', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (111, 49, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (112, 50, 'Île-de-France', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (113, 51, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (114, 52, 'Bretagne', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (115, 53, 'Corse', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (116, 54, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (117, 55, 'Pays de la Loire', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (118, 56, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (119, 57, 'Île-de-France', 'Autre', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (120, 18, 'Normandie', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (121, 19, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (122, 20, 'Corse', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (123, 21, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (124, 22, 'Pays de la Loire', 'Autre', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (125, 23, 'Guyane', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (126, 24, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (127, 25, 'Normandie', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (128, 26, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (129, 27, 'Corse', 'Autre', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (130, 28, 'Grand-Est', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (131, 29, 'Pays de la Loire', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (132, 30, 'Guyane', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (133, 31, 'Île-de-France', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (134, 32, 'Normandie', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (135, 33, 'Bretagne', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (136, 34, 'Corse', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (137, 35, 'Grand-Est', 'Études supérieures', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (138, 36, 'Pays de la Loire', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (139, 37, 'Guyane', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (140, 38, 'Île-de-France', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (141, 39, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (142, 40, 'Bretagne', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (143, 41, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (144, 42, 'Grand-Est', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (145, 43, 'Pays de la Loire', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (146, 44, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (147, 45, 'Île-de-France', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (148, 46, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (149, 47, 'Bretagne', 'Autre', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (150, 48, 'Corse', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (151, 49, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (152, 50, 'Pays de la Loire', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (153, 51, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (154, 52, 'Île-de-France', 'Autre', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (155, 53, 'Normandie', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (156, 54, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (157, 55, 'Corse', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (158, 56, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (159, 57, 'Pays de la Loire', 'Autre', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (160, 18, 'Guyane', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (161, 19, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (162, 20, 'Normandie', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (163, 21, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (164, 22, 'Corse', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (165, 23, 'Grand-Est', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (166, 24, 'Pays de la Loire', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (167, 25, 'Guyane', 'Études supérieures', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (168, 26, 'Île-de-France', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (169, 27, 'Normandie', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (170, 28, 'Bretagne', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (171, 29, 'Corse', 'Activité professionnelle en milieu ordinaire', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (172, 30, 'Grand-Est', 'Études supérieures', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (173, 31, 'Pays de la Loire', 'Sans aucune activité scolaire ou professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (174, 32, 'Guyane', 'Autre', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (175, 33, 'Île-de-France', 'Formation professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (176, 34, 'Normandie', 'Activité professionnelle en milieu ordinaire', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (177, 35, 'Bretagne', 'Études supérieures', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (178, 36, 'Corse', 'Sans aucune activité scolaire ou professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (179, 37, 'Grand-Est', 'Autre', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (180, 38, 'Pays de la Loire', 'Formation professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (181, 39, 'Guyane', 'Activité professionnelle en milieu ordinaire', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (182, 40, 'Île-de-France', 'Études supérieures', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (183, 41, 'Normandie', 'Sans aucune activité scolaire ou professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (184, 42, 'Bretagne', 'Autre', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (185, 43, 'Corse', 'Formation professionnelle', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (186, 44, 'Grand-Est', 'Activité professionnelle en milieu ordinaire', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (187, 45, 'Pays de la Loire', 'Études supérieures', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (188, 46, 'Guyane', 'Sans aucune activité scolaire ou professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE),
    (189, 47, 'Île-de-France', 'Autre', 'Dans une MAS', 'Oui', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (190, 48, 'Normandie', 'Formation professionnelle', 'Dans une FAM', 'Non', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (191, 49, 'Bretagne', 'Activité professionnelle en milieu ordinaire', 'Autre', 'Aucune', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (192, 50, 'Corse', 'Études supérieures', 'Dans la Famille en permanence', 'Oui', true, 'Autonome', 'aucun', CURRENT_DATE),
    (193, 51, 'Grand-Est', 'Sans aucune activité scolaire ou professionnelle', 'Dans un habitat inclusif', 'Non', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (194, 52, 'Pays de la Loire', 'Autre', 'Dans un logement indépendant', 'Aucune', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (195, 53, 'Guyane', 'Formation professionnelle', 'Dans une MAS', 'Oui', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (196, 54, 'Île-de-France', 'Activité professionnelle en milieu ordinaire', 'Dans une FAM', 'Non', true, 'Autonome', 'aucun', CURRENT_DATE),
    (197, 55, 'Normandie', 'Études supérieures', 'Autre', 'Aucune', false, 'Stimulations-ponctuelles', 'aucun', CURRENT_DATE),
    (198, 56, 'Bretagne', 'Sans aucune activité scolaire ou professionnelle', 'Dans la Famille en permanence', 'Oui', true, 'Soutien-autonomie', 'aucun', CURRENT_DATE),
    (199, 57, 'Corse', 'Autre', 'Dans un habitat inclusif', 'Non', false, 'Aide-24h', 'aucun', CURRENT_DATE),
    (200, 18, 'Grand-Est', 'Formation professionnelle', 'Dans un logement indépendant', 'Aucune', true, 'Autonome', 'aucun', CURRENT_DATE);